name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: EventGate.sln  # Replace with your solution name.
      AZURE_WEBAPP_NAME: eventgateapi
      AZURE_WEBAPP_PACKAGE_PATH: "./publish"

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Add MSBuild to the PATH
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Restore the application with verbose logging
    - name: Restore the application
      run: msbuild ${{ env.Solution_Name }} /t:Restore /p:Configuration=${{ matrix.configuration }} -verbosity:diag
      env:
        Configuration: ${{ matrix.configuration }}

    # Verify solution file exists
    - name: Verify solution file exists
      run: |
        if [ ! -f ${{ env.Solution_Name }} ]; then
          echo "Solution file not found: ${{ env.Solution_Name }}"
          exit 1
        fi

    # Build the application with verbose logging
    - name: Build
      run: msbuild ${{ env.Solution_Name }} /p:Configuration=${{ matrix.configuration }} -verbosity:diag
      env:
        Configuration: ${{ matrix.configuration }}

    # Verify build output directory
    - name: Verify build output
      run: |
        if [ ! -d ${{ env.AZURE_WEBAPP_PACKAGE_PATH }} ]; then
          echo "Build output directory not found: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
          exit 1
        fi

    # Publish
    - name: Publish
      run: dotnet publish ${{ env.Solution_Name }} --configuration Release --no-build --output ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    # Verify publish output directory
    - name: Verify publish output
      run: |
        if [ ! -d ${{ env.AZURE_WEBAPP_PACKAGE_PATH }} ]; then
          echo "Publish output directory not found: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
          exit 1
        fi

    # Deploy to Azure Web Apps
    - name: Deploy to Azure Web Apps
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
